##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Jean Julien Bourgault
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: An exhibit highlighting the artwork of Jean Julien Bourgault and the Franco-American Community of Lewiston-Auburn Maine
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: Jean Julien Bourgault was a Canadian artist whose speciality was wood carved sculptures. He was born in St-Jean-Port-Joli in 1910. He was born into a family of artists, where his father and brother worked as carpenters but were also wood carvers in their spare time. His uncle, Albert Legros, was a primitive sculptor, and likely inspired Jean Julien. Growing up J.J. was involved in a variety of jobs and artistic adventures. He took cabinet making courses in Quebec. He was an assistant keeper of the St-Jean-Port-Joli stone lighthouse for a time. He also was a navigator from Montreal to Newfoundland for a time. Though his passion for woodcarving inclined him to return to his village to work as a carpenter with his father and brother. He also worked with one of his other brothers in a carving studio. Together with his brother’s they were able to open a studio where they pursued their artistic talents. The reputation soon spread across Canada and the Franco-American Community of Maine. The artwork of Jean Julien Bourgault reflects his culture and heritage. What was truly unique about what they chose as their subject is that they are regular people. The subjects of the sculptors were related to the folklore of the region. The Bourgault family along with many other artists at the time were determined to preserve the past and their culture. So they would create artwork of peasants and fishermen and ordinary people. The geography and culture played an important role in the artwork of J.J. Bourgault. There was plenty of wood around due to the topography of Quebec Additionally wood was easy to acquire and he was likely already familiar with it, so it made for an easy medium. Additionally J.J. Bourgault was Catholic and many of his pieces reflect his religion. They have a religious undertone or have religious aspects such as crosses or other religious items being used. It has been stated that he is one of the most renowned clay, granite, and wood sculptures in the Western World. It was from April 24 to May 8 1977 that Jean Julien Bourgault had a sculpture exhibit at the Treat Gallery of Bates College. It was coordinated by Joanne LaPointe who was the curator of Franco-American Center d’Heritage at the time. Joanne had been in contact with Mr. Bourgault since early March to get the exhibit set up. There was a newspaper article published on April 16, 1977 detailing information about Jean Julien Bourgault and the important details of the upcoming exhibition at Bates College. The exhibit was important because it celebrated a French Canadian artist. This was important because the community of the Lewiston-Auburn area was Franco-American and this was important to their history and culture. The culture of Franco-American life was based heavily on families and having a community. The simple characters but intricate details of J.J. Bourgault’s work likely resonated with a lot of the people within the community. Music was also a large part of Franco-American life, therefore the arts were important and the community wanted to celebrate music and artwork. Another important aspect of J.J. Bourgault’s artistic career was the sculpting school he founded in 1958. The students came from all over Canada and the United States. The motivation behind starting the school was to honor the legacy of his father and the work of his older brothers. He was also looking to pass on his ‘craft’ to his children and the students at the school. It highlights the significance of community to J.J. because of the want to show others the wood carving craft and preserve the local stories and history of the people through artwork. Throughout his life J.J. Bourgault had exhibits at the Louvre in Paris, as well as in Berlin and New York, and his work could have been found in the private collections of former French Presidents Vincent Aurial and Charles de Gaulle as well as Queen Elizabeth II, Princess Margaret and Lord Beaverbrook of England, and Vincent Massey, minister commerce of Belgium. His artwork can also be found in the Sainte-Anne-de-la-Pocatière, l’église Saint-Charles Garnier de Sillery, and l’église de St.Jean-Port-Joli. He has been popularized with starting a renaissance of woodcarving in the twentieth century and some of his more popular works include large reliefs and religious sculptures. He has received several awards throughout his lifetime. In 1964 he received the Ordre National du Mérite from France. Then in 1970 he was given The Order of Canada which is given to people who make extraordinary contributions to the country. Then in 1993 he was celebrated as A Grand Officer of the Order of Quebec. His legacy persists in the artwork that he has created along with the artists he has inspired. 
 

author: Lydia

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: demo-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
